/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhitls_sdf4j_SDF */

#ifndef _Included_org_openhitls_sdf4j_SDF
#define _Included_org_openhitls_sdf4j_SDF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_OpenDevice
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1OpenDevice
  (JNIEnv *, jobject);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_CloseDevice
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1CloseDevice
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_OpenSession
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1OpenSession
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_CloseSession
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1CloseSession
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_GetDeviceInfo
 * Signature: (J)Lorg/openhitls/sdf4j/types/DeviceInfo;
 */
JNIEXPORT jobject JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1GetDeviceInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_GenerateRandom
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1GenerateRandom
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_GetPrivateKeyAccessRight
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1GetPrivateKeyAccessRight
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_ReleasePrivateKeyAccessRight
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1ReleasePrivateKeyAccessRight
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_ExportSignPublicKey_RSA
 * Signature: (JI)Lorg/openhitls/sdf4j/types/RSAPublicKey;
 */
JNIEXPORT jobject JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1ExportSignPublicKey_1RSA
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_ExportEncPublicKey_RSA
 * Signature: (JI)Lorg/openhitls/sdf4j/types/RSAPublicKey;
 */
JNIEXPORT jobject JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1ExportEncPublicKey_1RSA
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_ExportSignPublicKey_ECC
 * Signature: (JI)Lorg/openhitls/sdf4j/types/ECCPublicKey;
 */
JNIEXPORT jobject JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1ExportSignPublicKey_1ECC
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_ExportEncPublicKey_ECC
 * Signature: (JI)Lorg/openhitls/sdf4j/types/ECCPublicKey;
 */
JNIEXPORT jobject JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1ExportEncPublicKey_1ECC
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_DestroyKey
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1DestroyKey
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_InternalSign_ECC
 * Signature: (JI[B)Lorg/openhitls/sdf4j/types/ECCSignature;
 */
JNIEXPORT jobject JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1InternalSign_1ECC
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_InternalVerify_ECC
 * Signature: (JI[BLorg/openhitls/sdf4j/types/ECCSignature;)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1InternalVerify_1ECC
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jobject);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_ExternalVerify_ECC
 * Signature: (JILorg/openhitls/sdf4j/types/ECCPublicKey;[BLorg/openhitls/sdf4j/types/ECCSignature;)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1ExternalVerify_1ECC
  (JNIEnv *, jobject, jlong, jint, jobject, jbyteArray, jobject);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_ExternalEncrypt_ECC
 * Signature: (JILorg/openhitls/sdf4j/types/ECCPublicKey;[B)Lorg/openhitls/sdf4j/types/ECCCipher;
 */
JNIEXPORT jobject JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1ExternalEncrypt_1ECC
  (JNIEnv *, jobject, jlong, jint, jobject, jbyteArray);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_Encrypt
 * Signature: (JJI[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1Encrypt
  (JNIEnv *, jobject, jlong, jlong, jint, jbyteArray, jbyteArray);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_Decrypt
 * Signature: (JJI[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1Decrypt
  (JNIEnv *, jobject, jlong, jlong, jint, jbyteArray, jbyteArray);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_CalculateMAC
 * Signature: (JJI[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1CalculateMAC
  (JNIEnv *, jobject, jlong, jlong, jint, jbyteArray, jbyteArray);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_HashInit
 * Signature: (JILorg/openhitls/sdf4j/types/ECCPublicKey;[B)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1HashInit
  (JNIEnv *, jobject, jlong, jint, jobject, jbyteArray);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_HashUpdate
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1HashUpdate
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_openhitls_sdf4j_SDF
 * Method:    SDF_HashFinal
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openhitls_sdf4j_SDF_SDF_1HashFinal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
