/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhitls_sdf4j_internal_NativeLibraryLoader */

#ifndef _Included_org_openhitls_sdf4j_internal_NativeLibraryLoader
#define _Included_org_openhitls_sdf4j_internal_NativeLibraryLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhitls_sdf4j_internal_NativeLibraryLoader
 * Method:    nativeLoadSDFLibrary
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openhitls_sdf4j_internal_NativeLibraryLoader_nativeLoadSDFLibrary
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
